<?php
/**
 * Empower Pro Blocks child theme.
 *
 * @package Empower_Pro_Blocks
 * @author  Web Plant Media
 * @license GPL-2.0+
 * @link    https://webplantmedia.com/product/empower-pro-blocks/
 */

return array(
	'dependencies'     => array(
		'plugins' => array(
			array(
				'name'       => __( 'Atomic Blocks', 'empower-pro-blocks' ),
				'slug'       => 'atomic-blocks/atomicblocks.php',
				'public_url' => 'https://atomicblocks.com/',
			),
			array(
				'name'       => __( 'WooCommerce', 'empower-pro-blocks' ),
				'slug'       => 'woocommerce/woocommerce.php',
				'public_url' => 'https://wordpress.org/plugins/woocommerce/',
			),
			array(
				'name'       => __( 'WooCommerce Admin', 'empower-pro-blocks' ),
				'slug'       => 'woocommerce-admin/woocommerce-admin.php',
				'public_url' => 'https://wordpress.org/plugins/woocommerce-admin/',
			),
			array(
				'name'       => __( 'WPForms Lite (Third Party)', 'empower-pro-blocks' ),
				'slug'       => 'wpforms-lite/wpforms.php',
				'public_url' => 'https://wordpress.org/plugins/wpforms-lite/',
			),
			array(
				'name'       => __( 'Genesis Connect for WooCommerce', 'empower-pro-blocks' ),
				'slug'       => 'genesis-connect-woocommerce/genesis-connect-woocommerce.php',
				'public_url' => 'https://wordpress.org/plugins/genesis-connect-woocommerce/',
			),
			array(
				'name'       => __( 'WooCommerce Blocks', 'empower-pro-blocks' ),
				'slug'       => 'woo-gutenberg-products-block/woocommerce-gutenberg-products-block.php',
				'public_url' => 'https://wordpress.org/plugins/woo-gutenberg-products-block/',
			),
			array(
				'name'       => __( 'Genesis Portfolio Pro', 'empower-pro-blocks' ),
				'slug'       => 'genesis-portfolio-pro/genesis-portfolio-pro.php',
				'public_url' => 'https://wordpress.org/plugins/genesis-portfolio-pro/',
			),
			array(
				'name'       => __( 'Simple Social Icons', 'empower-pro-blocks' ),
				'slug'       => 'simple-social-icons/simple-social-icons.php',
				'public_url' => 'https://wordpress.org/plugins/simple-social-icons/',
			),
			array(
				'name'       => __( 'Genesis eNews Extended (Third Party)', 'empower-pro-blocks' ),
				'slug'       => 'genesis-enews-extended/plugin.php',
				'public_url' => 'https://wordpress.org/plugins/genesis-enews-extended/',
			),
			array(
				'name'       => __( 'Smash Balloon Social Photo Feed', 'empower-pro-blocks' ),
				'slug'       => 'instagram-feed/instagram-feed.php',
				'public_url' => 'https://wordpress.org/plugins/instagram-feed/',
			),
			array(
				'name'       => __( 'weDocs', 'empower-pro-blocks' ),
				'slug'       => 'wedocs/wedocs.php',
				'public_url' => 'https://wordpress.org/plugins/wedocs/',
			),
			array(
				'name'       => __( 'Regenerate Thumbnails', 'empower-pro-blocks' ),
				'slug'       => 'regenerate-thumbnails/regenerate-thumbnails.php',
				'public_url' => 'https://wordpress.org/plugins/regenerate-thumbnails/',
			),
			array(
				'name'       => __( 'Imsanity', 'empower-pro-blocks' ),
				'slug'       => 'imsanity/imsanity.php',
				'public_url' => 'https://wordpress.org/plugins/imsanity/',
			),
			array(
				'name'       => __( 'Responsive WordPress Slider - Soliloquy Lite', 'empower-pro-blocks' ),
				'slug'       => 'soliloquy-lite/soliloquy-lite.php',
				'public_url' => 'https://wordpress.org/plugins/soliloquy-lite/',
			),
		),
	),
	'content'          => array(
		'homepage'            => array(
			'post_title'     => 'Home',
			'post_name'      => 'homepage',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/homepage.php',
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'page_template'  => 'template-blocks.php',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		),
		'homepage-2'          => array(
			'post_title'     => 'Home 2',
			'post_name'      => 'homepage-2',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/homepage-2.php',
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'page_template'  => 'template-blocks.php',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		),
		'gutenberg-optimized' => array(
			'post_title'     => 'Gutenberg Optimized',
			'post_name'      => 'gutenberg-optimized',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/gutenberg-optimized.php',
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		),
		'post-1'              => array(
			'post_title'     => 'Why White Space and Typography Matter in Minimal Design',
			'post_name'      => 'post-1',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/post.php',
			'post_type'      => 'post',
			'post_status'    => 'publish',
			'comment_status' => 'open',
			'ping_status'    => 'closed',
			'featured_image' => get_stylesheet_directory() . '/config/import/images/featured/image-1.jpg',
		),
		'post-2'              => array(
			'post_title'     => 'The Secret Method to Creating the Perfect Amount of Simple',
			'post_name'      => 'post-2',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/post.php',
			'post_type'      => 'post',
			'post_status'    => 'publish',
			'comment_status' => 'open',
			'ping_status'    => 'closed',
			'featured_image' => get_stylesheet_directory() . '/config/import/images/featured/image-3.jpg',
		),
		'post-3'              => array(
			'post_title'     => 'Why Quality Matters When Sourcing Your Products',
			'post_name'      => 'post-3',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/post.php',
			'post_type'      => 'post',
			'post_status'    => 'publish',
			'comment_status' => 'open',
			'ping_status'    => 'closed',
			'featured_image' => get_stylesheet_directory() . '/config/import/images/featured/image-6.jpg',
		),
		'post-4'              => array(
			'post_title'     => 'Understanding the Differences of Good and Great',
			'post_name'      => 'post-4',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/post.php',
			'post_type'      => 'post',
			'post_status'    => 'publish',
			'comment_status' => 'open',
			'ping_status'    => 'closed',
			'featured_image' => get_stylesheet_directory() . '/config/import/images/featured/image-7.jpg',
		),
		'product-1'           => array(
			'post_title'     => 'Sweet + Simple',
			'post_name'      => 'product-1',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/product.php',
			'post_excerpt'   => require dirname( __FILE__ ) . '/import/content/product-excerpt.php',
			'post_type'      => 'product',
			'post_status'    => 'publish',
			'comment_status' => 'open',
			'ping_status'    => 'closed',
			'featured_image' => get_stylesheet_directory() . '/config/import/images/featured/image-9.jpg',
			'meta_input'     => array(
				'_regulary_price' => '11',
				'_price'          => '11',
			),
		),
		'product-2'           => array(
			'post_title'     => 'Cute Cutting Board',
			'post_name'      => 'product-2',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/product.php',
			'post_excerpt'   => require dirname( __FILE__ ) . '/import/content/product-excerpt.php',
			'post_type'      => 'product',
			'post_status'    => 'publish',
			'comment_status' => 'open',
			'ping_status'    => 'closed',
			'featured_image' => get_stylesheet_directory() . '/config/import/images/featured/image-8.jpg',
			'meta_input'     => array(
				'_regulary_price' => '20',
				'_price'          => '20',
			),
		),
		'product-3'           => array(
			'post_title'     => 'Flowers in a Crate',
			'post_name'      => 'product-3',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/product.php',
			'post_excerpt'   => require dirname( __FILE__ ) . '/import/content/product-excerpt.php',
			'post_type'      => 'product',
			'post_status'    => 'publish',
			'comment_status' => 'open',
			'ping_status'    => 'closed',
			'featured_image' => get_stylesheet_directory() . '/config/import/images/featured/image-5.jpg',
			'meta_input'     => array(
				'_regulary_price' => '18',
				'_price'          => '18',
			),
		),
		'product-4'           => array(
			'post_title'     => 'Cute Flowers',
			'post_name'      => 'product-4',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/product.php',
			'post_excerpt'   => require dirname( __FILE__ ) . '/import/content/product-excerpt.php',
			'post_type'      => 'product',
			'post_status'    => 'publish',
			'comment_status' => 'open',
			'ping_status'    => 'closed',
			'featured_image' => get_stylesheet_directory() . '/config/import/images/featured/image-2.jpg',
			'meta_input'     => array(
				'_regulary_price' => '20',
				'_price'          => '20',
			),
		),
		'blog'                => array(
			'post_title'     => 'Blog',
			'post_name'      => 'blog',
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		),
		'instagram-page'      => array(
			'post_title'     => 'Instagram Page',
			'post_name'      => 'instagram-page',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/instagram-page.php',
			'post_type'      => 'page',
			'page_template'  => 'template-blocks.php',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		),
		'landing-page'        => array(
			'post_title'     => 'Landing Page',
			'post_name'      => 'landing-page',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/landing-page.php',
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'page_template'  => 'page-landing.php',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		),
		'contact'             => array(
			'post_title'     => 'Contact',
			'post_name'      => 'contact-page',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/contact-page.php',
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
			'meta_input'     => array(
				'_genesis_layout' => 'full-width-content',
			),
		),
		'typography-page'     => array(
			'post_title'     => 'Typography Page',
			'post_name'      => 'typography-page',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/typography-page.php',
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
			'meta_input'     => array(
				'_genesis_layout' => 'full-width-content',
			),
		),
		'pricing-table'       => array(
			'post_title'     => 'Pricing Table',
			'post_name'      => 'pricing-table',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/pricing-table.php',
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
			'meta_input'     => array(
				'_genesis_layout' => 'full-width-content',
			),
		),
		'faq'                 => array(
			'post_title'     => 'FAQ',
			'post_name'      => 'faq',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/wedocs-page.php',
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
			'meta_input'     => array(
				'_genesis_layout' => 'full-width-content',
			),
		),
		'shop'                => array(
			'post_title'     => 'Shop',
			'post_name'      => 'shop',
			'post_type'      => 'page',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		),
		'cart'                => array(
			'post_title'     => 'Cart',
			'post_name'      => 'cart',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/cart-page.php',
			'post_type'      => 'page',
			'page_template'  => 'page-fullwidth-no-cta.php',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		),
		'checkout'            => array(
			'post_title'     => 'Checkout',
			'post_name'      => 'checkout',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/checkout-page.php',
			'post_type'      => 'page',
			'page_template'  => 'page-fullwidth-no-cta.php',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		),
		'my-account'          => array(
			'post_title'     => 'My Account',
			'post_name'      => 'my-account',
			'post_content'   => require dirname( __FILE__ ) . '/import/content/my-account-page.php',
			'post_type'      => 'page',
			'page_template'  => 'page-no-cta.php',
			'post_status'    => 'publish',
			'comment_status' => 'closed',
			'ping_status'    => 'closed',
		),
	),
	'navigation_menus' => array(
		'primary'   => array(
			'homepage'            => array(
				'title' => 'Home',
			),
			'homepage-2'          => array(
				'title'  => 'Home 2',
				'parent' => 'homepage',
			),
			'gutenberg-optimized' => array(
				'title' => 'Gutenberg Optimized',
			),
			'instagram-page'      => array(
				'title'  => 'Instagram Page',
				'parent' => 'gutenberg-optimized',
			),
			'contact'             => array(
				'title'  => 'Contact',
				'parent' => 'gutenberg-optimized',
			),
			'landing-page'        => array(
				'title'  => 'Landing Page',
				'parent' => 'gutenberg-optimized',
			),
			'typography-page'     => array(
				'title'  => 'Typography Page',
				'parent' => 'gutenberg-optimized',
			),
			'pricing-table'       => array(
				'title'  => 'Pricing Table',
				'parent' => 'gutenberg-optimized',
			),
			'faq'                 => array(
				'title' => 'FAQ',
			),
			'blog'                => array(
				'title' => 'Blog',
			),
			'shop'                => array(
				'title' => 'Shop',
			),
		),
		'secondary' => array(
			'homepage'            => array(
				'title' => 'Home',
			),
			'gutenberg-optimized' => array(
				'title' => 'Gutenberg Optimized',
			),
			'shop'                => array(
				'title' => 'Shop',
			),
		),
	),
	'widgets'          => array(
		'sidebar'             => array(
			array(
				'type' => 'featured-post',
				'args' => array(
					'title'                   => 'Featured Posts',
					'posts_cat'               => '18',
					'posts_num'               => 1,
					'posts_offset'            => '7',
					'orderby'                 => 'date',
					'order'                   => 'DESC',
					'gravatar_size'           => '45',
					'gravatar_alignment'      => 'alignnone',
					'show_image'              => '1',
					'image_size'              => 'medium_large',
					'image_alignment'         => 'alignnone',
					'show_title'              => '1',
					'post_info'               => '[post_date] By [post_author_posts_link] [post_comments]',
					'show_content'            => 'excerpt',
					'content_limit'           => '0',
					'more_text'               => "Continue Reading \u2192",
					'extra_title'             => '',
					'extra_num'               => '',
					'more_from_category'      => '1',
					'more_from_category_text' => 'More Posts from this Category',
				),
			),
			array(
				'type' => 'enews-ext',
				'args' => array(
					'title'           => 'Newsletter',
					'text'            => 'Sign up to receive email updates and to hear what\'s going on with our company!',
					'after_text'      => '',
					'id'              => '',
					'action'          => '#',
					'email-field'     => '#',
					'fname-field'     => '',
					'lname-field'     => '',
					'hidden_fields'   => '',
					'fname_text'      => 'First Name',
					'lname_text'      => 'Last Name',
					'input_text'      => 'E-Mail Address',
					'button_text'     => 'Go',
					'display_privacy' => 0,
				),
			),
			array(
				'type' => 'search',
				'args' => array(
					'title' => '',
				),
			),
			array(
				'type' => 'simple-social-icons',
				'args' => array(
					'title'                  => 'Connect',
					'size'                   => '36',
					'border_radius'          => '999',
					'border_width'           => '0',
					'alignment'              => 'alignleft',
					'icon_color'             => '#ffffff',
					'icon_color_hover'       => '#ffffff',
					'background_color'       => '#134277',
					'background_color_hover' => '#27568b',
					'border_color'           => '#ffffff',
					'border_color_hover'     => '#ffffff',
					'behance'                => '',
					'bloglovin'              => '',
					'dribbble'               => '',
					'email'                  => '#',
					'facebook'               => '#',
					'flickr'                 => '',
					'github'                 => '',
					'gplus'                  => '',
					'instagram'              => '#',
					'linkedin'               => '',
					'medium'                 => '',
					'periscope'              => '',
					'phone'                  => '',
					'pinterest'              => '#',
					'rss'                    => '',
					'snapchat'               => '',
					'stumbleupon'            => '',
					'tumblr'                 => '',
					'twitter'                => '',
					'vimeo'                  => '',
					'xing'                   => '',
					'youtube'                => '#',
				),
			),
			array(
				'type' => 'categories',
				'args' => array(
					'title'        => 'Categories',
					'count'        => 0,
					'hierarchical' => 0,
					'dropdown'     => 1,
				),
			),
			array(
				'type' => 'meta',
				'args' => array(
					'title' => 'Navigation',
				),
			),
		),
		'above-footer-cta'    => array(
			array(
				'type' => 'custom_html',
				'args' => array(
					'title'   => 'Get 50% Off Your First Order',
					'content' => '<a href="#" class="button button-hero">Browse our Coffee Selections</a>',
				),
			),
		),
		'above-footer-image'  => array(
			array(
				'type' => 'media_image',
				'args' => array(
					'size'              => 'full',
					'width'             => 1920,
					'height'            => 1280,
					'caption'           => '',
					'alt'               => '',
					'link_type'         => 'custom',
					'link_url'          => '',
					'image_classes'     => '',
					'link_classes'      => '',
					'link_rel'          => '',
					'link_target_blank' => false,
					'image_title'       => '',
					'attachment_id'     => 23,
					'url'               => CHILD_URL . '/config/import/images/image-10.jpg',
					'title'             => '',
				),
			),
		),
		'empower-pro-blocks-footer' => array(
			array(
				'type' => 'custom_html',
				'args' => array(
					'title'   => 'Contact Info',
					'content' => '<h4>Marketing Agency</h4>
<p>
1651202 Main street<br />
Anytown, USA<br />
t:+1 (555) 555-1234<br />
f: +1 (555) 555-5678<br />
</p>',
				),
			),
			array(
				'type' => 'meta',
				'args' => array(
					'title' => 'Navigation',
				),
			),
			array(
				'type' => 'enews-ext',
				'args' => array(
					'title'           => 'Newsletter',
					'text'            => 'Sign up to receive email updates and to hear what’s going on with our company!',
					'after_text'      => '',
					'id'              => '',
					'action'          => '#',
					'email-field'     => '#',
					'fname-field'     => '',
					'lname-field'     => '',
					'hidden_fields'   => '',
					'fname_text'      => 'First Name',
					'lname_text'      => 'Last Name',
					'input_text'      => 'E-Mail Address',
					'button_text'     => 'Go →',
					'display_privacy' => 0,
				),
			),
		),
	),
);
